Feat/search user page
BSM-GG/BSM.GG-Frontend pull request #6
Opened 2023-08-08 12:34 UTC by lsj0202

유저페이지 만들었음

2023-08-09 11:39 UTC, SEOKKAMONI requested changes

2023-08-09 11:39 UTC, SEOKKAMONI commented on src/App.tsx
> +    </>
```suggestion
      <RankPage />
```

?

2023-08-09 11:39 UTC, SEOKKAMONI commented on src/components/svg/searchIcon700.tsx
> +    >
```suggestion
import React from 'react';
import type { SVGProps } from 'react';

const SearchIcon = (props: SVGProps<SVGSVGElement>) => {
  return (
    <svg
      viewBox="0 0 26 26"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
```

이건 어떠신지

2023-08-09 11:39 UTC, SEOKKAMONI commented on src/pages/schoolRankPage/index.tsx
> +import { dummy } from "../../dummy/userRank.dummy";
좀 더 자세한 네이밍은 어떨까요

2023-08-09 11:39 UTC, SEOKKAMONI commented on src/pages/schoolRankPage/style.ts
> +  align-items: center;
https://slash.page/ko/libraries/react/emotion-utils/src/flex.i18n

toss에 이런것도있는데 계속해서 중복되는 부분이기도 하고 3줄을 1줄로 줄일수있으니 써봐도 좋을것같아요

2023-08-09 11:40 UTC, SEOKKAMONI commented on src/pages/schoolRankPage/index.tsx
> +import { dummy } from "../../dummy/userRank.dummy";
dummy 말한거임

2023-08-09 11:43 UTC, rlawnsrud0509 commented on src/pages/schoolRankPage/style.ts
> +  align-items: center;
알았지상진

2023-08-09 11:44 UTC, Ubinquitous commented on src/components/svg/searchIcon700.tsx
> +    >
구려요

2023-08-09 11:44 UTC, SEOKKAMONI commented on src/components/svg/searchIcon700.tsx
> +    >
너 쓰기만해봐

2023-08-09 11:49 UTC, Ubinquitous approved these changes

2023-08-09 11:49 UTC, Ubinquitous commented on src/components/svg/searchIcon700.tsx
> +    >
SVGSVGElement가뭔데

2023-08-09 11:49 UTC, Ubinquitous commented on src/pages/schoolRankPage/index.tsx
> +            <S.UserWrapper key={index}>
key를 index로 주면 많은문제가생깁니다

2023-08-09 11:49 UTC, Ubinquitous commented on src/pages/schoolRankPage/index.tsx
> +              <S.Lp>{data.lp} LP</S.Lp>
네이밍 너무줄인것같아요..

2023-08-09 11:49 UTC, Ubinquitous commented on src/pages/schoolRankPage/index.tsx
> +              <S.Win2>{data.win} %</S.Win2>
더 명시적인 네이밍이필요해요

2023-08-09 11:49 UTC, Ubinquitous commented on src/pages/schoolRankPage/index.tsx
> +            <S.ArrowNav onClick={onClickNextPage}> {">"} </S.ArrowNav>
svg쓰세요 귀찮아도

2023-08-09 11:51 UTC, SEOKKAMONI commented on src/components/svg/searchIcon700.tsx
> +    >
그러게 저거는 의문이긴하다 왜 SVG * 2지

2023-08-09 11:59 UTC, SEOKKAMONI commented on src/pages/schoolRankPage/index.tsx
> +              <S.Win2>{data.win} %</S.Win2>
Win2는 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-08-10 11:35 UTC, rlawnsrud0509 commented on src/components/svg/searchIcon700.tsx
> +    >
어떻게할까요 님들

2023-08-10 12:12 UTC, Ubinquitous commented on src/components/svg/searchIcon700.tsx
> +    >
사용하세요 좋은것같습니다^^..

2023-08-10 15:25 UTC, rlawnsrud0509 commented on src/App.tsx
> +    </>
?

2023-08-11 08:49 UTC, rlawnsrud0509 commented on src/pages/schoolRankPage/index.tsx
> +            <S.ArrowNav onClick={onClickNextPage}> {">"} </S.ArrowNav>
svg쓰라고 이상진 내가만들어뒀잖아

2023-08-11 08:49 UTC, rlawnsrud0509 commented on src/pages/schoolRankPage/index.tsx
> +              <S.Lp>{data.lp} LP</S.Lp>
좀길게적어라 자판고장나는것도아니고

2023-08-11 08:49 UTC, rlawnsrud0509 commented on src/pages/schoolRankPage/index.tsx
> +            <S.UserWrapper key={index}>
음

2023-08-17 04:59 UTC, lsj0202 commented on src/pages/schoolRankPage/style.ts
> +  align-items: center;
알앗서

2023-08-17 22:45 UTC, merged

2023-08-18 02:18 UTC, lsj0202 commented on src/pages/schoolRankPage/index.tsx
> +import { dummy } from "../../dummy/userRank.dummy";
더미데이터 네이밍도 중요한거였군요! 알겠습니당

2023-08-18 02:18 UTC, lsj0202 commented on src/pages/schoolRankPage/index.tsx
> +            <S.UserWrapper key={index}>
data.id로 주겠습니다.

2023-08-18 02:18 UTC, lsj0202 commented on src/pages/schoolRankPage/index.tsx
> +              <S.Lp>{data.lp} LP</S.Lp>
미안해..

2023-08-18 02:19 UTC, lsj0202 commented on src/pages/schoolRankPage/index.tsx
> +              <S.Win2>{data.win} %</S.Win2>
알겠습니다..

2023-08-18 02:19 UTC, lsj0202 commented on src/pages/schoolRankPage/index.tsx
> +            <S.ArrowNav onClick={onClickNextPage}> {">"} </S.ArrowNav>
네..